name: gaijin

on:
  schedule:
    # Türkiye saatiyle 13:00 → UTC 10:00
    - cron: "0 10 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests pandas certifi selenium webdriver-manager openpyxl

      - name: Run gaijin
        run: python gaijin.py

      - name: Upload CSV artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gaijin-output
          path: |
            gaijin.csv
            pivot_gaijin.csv
          retention-days: 3

      - name: Check pivot and convert to Excel
        run: python check_pivot.py

      - name: Upload Excel artifact
        uses: actions/upload-artifact@v4
        with:
          name: pivot-excel
          path: pivot_gaijin.xlsx
          retention-days: 3
