name: pdfk-all

on:
  schedule:
    # Türkiye saatiyle 13:00 → UTC 10:00
    - cron: "0 10 * * *"
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests pandas numpy openpyxl pytz

      - name: Run vert script
        run: python pdfk_vert.py

      - name: Run hor script
        run: python pdfk_hor.py

      - name: Upload vert artifact
        uses: actions/upload-artifact@v4
        with:
          name: vert-pdfk-excel
          path: pdfk_vert.xlsx
          retention-days: 3

      - name: Upload hor artifact
        uses: actions/upload-artifact@v4
        with:
          name: hor-pdfk-excel
          path: pdfk_hor.xlsx
          retention-days: 3
